"""empty message

Revision ID: 9437f92c165f
Revises: eb6dd1ce83d9
Create Date: 2019-01-25 12:56:28.405416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9437f92c165f'
down_revision = 'eb6dd1ce83d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('installation', sa.Column('enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installation', 'enabled')
    # ### end Alembic commands ###
