"""empty message

Revision ID: eb6dd1ce83d9
Revises: 67104ba82c98
Create Date: 2019-01-24 12:21:17.222415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6dd1ce83d9'
down_revision = '67104ba82c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('installation', 'install_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'installation', ['install_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'installation', type_='unique')
    op.alter_column('installation', 'install_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
